## 운영 환경

spring:
  application:
    name: travelmaker-prod
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # 페이징 +컬렉션 조회 최적화 (쓰는 이유를 알고,웬만하면 해당 옵션을 켜놓자)
        # in 쿼리의 개수를 설정
        default_batch_fetch_size: 100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(35Ri/9f4Hv2XEb8/ajB5Xw==)
    password: ENC(c9UeCbXeIgt1eH80thMPuis3icfdciYJnf7n3/cm48k=)
    url: ENC(CCSipdikBLPbdGrvZudyMLFL+hIKfNrp2t6JGYS57Qlg4/7UFZ5z/kvr+WCb90pOJk5wR0wkKsAl3M74nizbX3KdO7TaHk3tlW5kmGsFOAkJfHDy5cIwycVsbMOqmt3zzHkVHpLTb4eT0AfZJ3VXnDlAocEJPDoBN9J6CYsFN5+EYfng1a53SwZgDgalWjvd7+56tIOY+/6K8XHjF4Ey7Q==)

server:
  port: 8080

cloud:
  aws:
    s3:
      bucket: ENC(Y4/w6+PLIdoUTI9TcQf7/echDgJEldvj3uF8hXTHGqw=)
    credentials:
      access-key: ENC(d+zPWsAtzmUL8Ve0cxpeoGulXzgyrIsDzONSCglQAXo=)
      secret-key: ENC(7UzrnKPq0ZAolzrPxTRNC9tcbw0ETQzyrKDS5454M0YjOtPzVQOJQjqLPZbNSTLXzWDnLDyZq4o=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false