spring:
  security:
    jwt:
      header: Authorization
      secret: ENC(I23+H3zRfczCSQnICE7745gbu1wmyQoTPZ0btiqyFE7lX6ArnKUjSqP5NoyFMP+D)
      token-validity-in-seconds: 86400

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(P5J7Ioi0OprueUrt3fFv2A==)
    password: ENC(eCb5NnNqDSeixJJVCqt0Cw==)
    url: ENC(FfK3luDDW5RcfTf1Y1ANsU5fbfTK71q6ycvpGMufvdnRfihWWrBlpm6NV6l0liIOGAiXlQhyAK5JQJYcYhrKIzWfyKBYBLbB1hNl4kPyA64=)
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

cloud:
  aws:
    s3:
      bucket: ENC(Y4/w6+PLIdoUTI9TcQf7/echDgJEldvj3uF8hXTHGqw=)
    credentials:
      access-key: ENC(d+zPWsAtzmUL8Ve0cxpeoGulXzgyrIsDzONSCglQAXo=)
      secret-key: ENC(7UzrnKPq0ZAolzrPxTRNC9tcbw0ETQzyrKDS5454M0YjOtPzVQOJQjqLPZbNSTLXzWDnLDyZq4o=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

coolsms:
  apikey: ENC(vImbLVrEKhRcpw4V9SDzb65QF75toGAqYFQxP6w65W4)
  apisecret: ENC(tXtdAdiNRCXm8EPhD0/nuJDzSQ9LvDf72o5Oi3R51zC3YBvwGhs8yS+oJ+A11V9H)
  fromnumber: ENC(xh+4vRLXHZlgz/IrX/3SmOxtgjY3FMp9)

